// Minigames index - easy imports
export { BalanceGame } from './BalanceGame';
export { BreathingExercise } from './BreathingExercise';
export { ColorGame } from './ColorCalm';
export { ColorMatch } from './ColorMatch';
export { FortuneGame } from './DailyFortune';
export { MathBlitz } from './MathBlitz';
export { NumberGuesser } from './NumberGuesser';
export { PatternRepeat } from './PatternRepeat';
export { BubbleGame } from './PopBubbles';
export { PuzzleSlider } from './PuzzleSlider';
export { ReflexGame } from './ReflexGame';
export { SequenceGame } from './SequenceGame';
export { SimonSays } from './SimonSays';
export { SpeedTap } from './SpeedTap';
export { SpinWheel } from './SpinWheel';
export { SwitchGame } from './Switches';
export { TapCounter } from './TapCounter';
export { WordChain } from './WordChain';
export { GridGame } from './ZenGrid';
export { MemoryGame } from './ZenMatch';

